cd LVL7
mex mexLSExtend.c 
mex mexLSPropagate.c
mex mexLSReinit.c
mex mexLSReinit0.c
mex mexLSReOrtho.c
cd ..
cd ImageTools
mex mexImScalling2D.c
mex mexImScalling3D.c
mex mexInterpSpline.c
mex mexInterpLinearClosest.c
mex mexInterpLVL7.c
mex mexInterpLinear.c
mex mexInterpSpline3D.c
mex mexInterpLinear3D.c
mex mexPhidf3D.c
mex mexPhidf3Dp.c
mex mexPhidf2D.c
mex mexGradSpline.c
mex mexGradSpline3D.c
mex mexGradLinear3D.c
mex mexGradLinear.c
mex mexGradLinearWithMask.c
mex mexFDGradient.c
cd ..
cd BasisFunctions
mex GetFiniteElementShapeFunctions3D.c
mex GetFiniteElementShapeFunctions.c
cd ..
cd Integration
mex GetGaussPointsPixels.c
mex GetGaussPointsVoxels.c
cd ..
cd Solvers
mex mexInv66.c
cd ..
